### ISSUE TITLE
Not able to access baidu link 

### ISSUE THREAD

**Issue by nandini211995** [icey-zhang/GHOST#12]
Hi 
I am not able to access to baidu link for VEDAI dataset. Kindly provide google drive or one-drive link to access.

**Comment by icey-zhang** [comment]
Download VEDAI data for our experiment from [baiduyun](https://pan.baidu.com/s/1L0SWi5AQA6ZK9jDIWRY7Fg) (code: hvi4) or [google drive](https://drive.google.com/file/d/1Fz0VVlBS924pM3RQvcTsD_qaGjxzIv3y/view?usp=sharing). And the path of dataset is like that
