### ISSUE TITLE
Input and output sizes should be greater than 0, but got input (H: 16, W: 16) output (H: 0, W: 0)

### ISSUE THREAD

**Issue by melika-sce** [icey-zhang/GHOST#3]
Hi 
I tried to train an SRyolo model with VisDrone dataset, but this error occurs
any help would be appriciated!

***
Namespace(adam=False, artifact_alias='latest', batch_size=2, bbox_interval=-1, bucket='', cache_images=False, cfg='models/SRyolo_noFocus.yaml', ch=3, ch_steam=3, da
ta='data/VisDrone.yaml', device='0', entity=None, epochs=1, evolve=False, exist_ok=False, global_rank=-1, hr_input=True, hyp='data/hyp.scratch.yaml', image_weights=
False, img_size=[512, 512], input_mode='RGB', linear_lr=False, local_rank=-1, multi_scale=False, name='exp', noautoanchor=False, nosave=False, notest=False, project
='runs/train', quad=False, rect=False, resume=False, save_dir='runs\\train\\exp4', save_period=-1, single_cls=False, super=True, sync_bn=False, test_img_size=512, total_batch_size=2, train_img_size=512, upload_dataset=False, weights='', workers=4, world_size=1)
tensorboard: Start with 'tensorboard --logdir runs/train', view at http://localhost:6006/
hyperparameters: lr0=0.01, lrf=0.2, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=0.05, cls=0.5, cls_pw=1.0, 
obj=1.0, obj_pw=1.0, iou_t=0.2, anchor_t=4.0, kl_pw=1.0, fl_gamma=0.0, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, mosaic=1.0, mixup=0.0, copy_paste=0.1
wandb: Install Weights & Biases for YOLOv5 logging with 'pip install wandb' (recommended)
Overriding model.yaml nc=8 with nc=10

from             n    params             module                                  arguments
  0                -1  1       928  models.common.Conv                      [3, 32, 3, 1]
  1                -1  1     18560  models.common.Conv                      [32, 64, 3, 2]
  2                -1  1     18816  models.common.C3                        [64, 64, 1]                   
  3                -1  1     73984  models.common.Conv                      [64, 128, 3, 2]               
  4                -1  1    156928  models.common.C3                        [128, 128, 3]                 
  5                -1  1    295424  models.common.Conv                      [128, 256, 3, 2]              
  6                -1  1    625152  models.common.C3                        [256, 256, 3]                 
  7                -1  1   1180672  models.common.Conv                      [256, 512, 3, 2]              
  8                -1  1    656896  models.common.SPP                       [512, 512, [5, 9, 13]]        
  9                -1  1   1182720  models.common.C3                        [512, 512, 1, False]          
 10                -1  1    131584  models.common.Conv                      [512, 256, 1, 1]              
 11                -1  1         0  torch.nn.modules.upsampling.Upsample    [None, 2, 'nearest']
 12           [-1, 6]  1         0  models.common.Concat                    [1]
 13                -1  1    361984  models.common.C3                        [512, 256, 1, False]          
 14                -1  1     33024  models.common.Conv                      [256, 128, 1, 1]              
 15                -1  1         0  torch.nn.modules.upsampling.Upsample    [None, 2, 'nearest']
 16           [-1, 4]  1         0  models.common.Concat                    [1]
 17                -1  1     90880  models.common.C3                        [256, 128, 1, False]          
 18                -1  1    147712  models.common.Conv                      [128, 128, 3, 2]              
 19          [-1, 14]  1         0  models.common.Concat                    [1]
 20                -1  1    296448  models.common.C3                        [256, 256, 1, False]          
 21                -1  1    590336  models.common.Conv                      [256, 256, 3, 2]
 22          [-1, 10]  1         0  models.common.Concat                    [1]                           
 23                -1  1   1182720  models.common.C3                        [512, 512, 1, False]          
 24      [17, 20, 23]  1     40455  models.SRyolo.Detect                    [10, [[10, 13, 16, 30, 33, 23], [30, 61, 62, 45, 59, 119], [116, 90, 156, 198, 373, 326]], [128, 256, 512]]
Traceback (most recent call last):
  File "train.py", line 674, in <module>
    train(hyp, opt, device, tb_writer)
  File "train.py", line 103, in train
    model = Model(opt.cfg, input_mode = opt.input_mode ,ch_steam=opt.ch_steam,ch=opt.ch, nc=nc, anchors=hyp.get('anchors'),config=None,sr=opt.super,factor=down_factor).to(device)  # create
  File "N:\Master\Thesis\Code\KD\12row_third_try\GHOST\models\SRyolo.py", line 117, in __init__
    m.stride = torch.tensor([s / x.shape[-2] for x in self.forward(torch.zeros(1, ch_steam, s, s),torch.zeros(1, ch_steam, s, s),input_mode)[0]])  # forward        
  File "N:\Master\Thesis\Code\KD\12row_third_try\GHOST\models\SRyolo.py", line 190, in forward
    y,output_sr,features = self.forward_once(steam,'yolo', profile) #zjq
  File "N:\Master\Thesis\Code\KD\12row_third_try\GHOST\models\SRyolo.py", line 243, in forward_once
    output_sr = self.model_up(y[self.l1],y[self.l2]) #在超分上加attention
  File "C:\Users\__Melika__\miniconda3\envs\yolo\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "N:\Master\Thesis\Code\KD\12row_third_try\GHOST\models\deeplabedsr.py", line 60, in forward
    x_sr= self.sr_decoder(x, low_level_feat,self.factor)
  File "C:\Users\__Melika__\miniconda3\envs\yolo\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "N:\Master\Thesis\Code\KD\12row_third_try\GHOST\models\sr_decoder_noBN_noD.py", line 38, in forward
    x = F.interpolate(x, size=[i*(factor//2) for i in low_level_feat.size()[2:]], mode='bilinear', align_corners=True)
  File "C:\Users\__Melika__\miniconda3\envs\yolo\lib\site-packages\torch\nn\functional.py", line 3959, in interpolate
    return torch._C._nn.upsample_bilinear2d(input, output_size, align_corners, scale_factors)
RuntimeError: Input and output sizes should be greater than 0, but got input (H: 16, W: 16) output (H: 0, W: 0)
***

**Comment by icey-zhang** [comment]
You can refer to https://github.com/icey-zhang/SuperYOLO/issues/25

**Comment by melika-sce** [comment]
@icey-zhang Thank you, I follow the solution at that issue and it worked, but I have a question
I want to train SRyolo with both train_image_size and test_image_size equal to 1024, but when I set the down_factor= 2 in code (this was the solution provided in that issue), my train config shows different information

![Screenshot 2023-08-06 191514](https://github.com/icey-zhang/GHOST/assets/71076583/14c82ca5-27e3-4d4b-ae34-14388e9ce35e)

is it possible to train [SuperYolo](https://github.com/icey-zhang/SuperYOLO) with same train and test size?
and which of these information in the log is correct?
is the image size 512x512 or 1024x1024 or anything else?

Thanks

**Comment by icey-zhang** [comment]
Please set the train_image_size=1024, test_image_size=512 to use the super resolution branch

**Comment by melika-sce** [comment]
so the train_image_size must be double of  test_image_size, right?
can I set train_image_size=2048 and test_image_size=1024 to use the super resolution branch too?

**Comment by icey-zhang** [comment]
it is okay, and the code can run any factor. In our experiment, the 2x is the best！

**Comment by melika-sce** [comment]
Thanks!
