### ISSUE TITLE
关于论文中的指标问题

### ISSUE THREAD

**Issue by xiaoshuomin** [icey-zhang/GHOST#5]
![image](https://github.com/icey-zhang/GHOST/assets/43821417/3388af43-fcd2-406a-9bea-aa9cedf6dd29)
![image](https://github.com/icey-zhang/GHOST/assets/43821417/69198971-959b-4a08-9e95-590f5e91ac38)
作者您好，我看到您的论文中SuperYOLO的模型参数量与原论文报道的参数量不太一样，似乎都是在VEDAID数据集并使用512*512输入的情况下进行的统计，请问这是什么原因？

**Comment by icey-zhang** [comment]
GHOST用的是是三个检测头的SuperYOLO的代码，SuperYOLO用的是单检测头的（论文里写了）
